# Generated by Django 3.0.5 on 2020-05-03 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyTransferHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user_currency', models.CharField(max_length=21)),
                ('from_user_quantity', models.DecimalField(decimal_places=2, max_digits=19)),
                ('to_user_currency', models.CharField(max_length=21)),
                ('to_user_currency_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('to_user_quantity', models.DecimalField(decimal_places=2, max_digits=19)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ce_currency_transfer_history',
            },
        ),
    ]
