# Generated by Django 3.0.5 on 2020-05-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='currency_quantity',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
    ]
