# Generated by Django 3.0.5 on 2020-05-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20200503_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='currency_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
